---
- hosts: localhost
  user: joechiu
  become: yes
  vars:
    jenkins_home: /var/jenkins_home
    jenkins_local: /home/joechiu/jenkins
    image: myjenkins
    password: foobar
    sock: /var/run/docker.sock
    docker: /usr/bin/docker
    sysconfig: /etc/sysconfig/docker
    uid: 1000
  tasks:
    - name: clean up docker
      ignore_errors: yes
      shell: |
        docker stop $(docker ps -a -q)
        docker rm -f $(docker ps -a -q)
        docker rmi -f $(docker images -q)
      args:
        warn: no

    - name: Create jenkins directory beforehand
      file: path={{ jenkins_local }} state=directory owner={{uid}} mode=0755

    - name: Build a local jenkins docker container
      shell: |
        docker build --network=host -t {{image}} .
      args:
        warn: no

    - name: Run jenkins docker daemon
      shell: |
        docker run --net=host -v {{sock}}:{{sock}}:z -v {{jenkins_local}}:{{jenkins_home}}:z -d {{image}}
      args:
        warn: no

